### ISSUE TITLE
Using kebab-case for css properties in objects is not supported. Did you mean fontWeight?

### ISSUE THREAD

**Issue by Tim-arts** [geometricpanda/geometricpanda#30]
Hello, there's this error showing up in the console, I believe it's due to the changes adressed in 0.2.0 to give more controls about how to stylize the badges:

![image](https://user-images.githubusercontent.com/10064887/134222179-0ecd0fdc-791f-46c7-8b2c-169cce713241.png)

**Comment by jimdrury** [comment]
Ah yeah, I see what’s causing it. I’ll fix it this weekend.

**Comment by jimdrury** [comment]
That'll be released later today

**Comment by Tim-arts** [comment]
Great, thanks Jim!

**Comment by Tim-arts** [comment]
Actually the issue is still there sadly :/

**Comment by Tim-arts** [comment]
Seems I had a cache issue, it seems gone.. Sorry for the false positive mate! By the way, thank you very much for the daily dedication you put into this repo!
