### ISSUE TITLE
Use storybook as a peerDependency instead of a dependency

### ISSUE THREAD

**Issue by Samuel-Schober-USU** [geometricpanda/geometricpanda#32]
# 🚀 feature request

### Relevant Package

 The issue is caused by package @gemetricpanda/storybook-addon-iframe

### Description
It seems that the package does not work with storybook `^6.3.8` , since the tab in the Storybook is just not added. 

To evaluate it, I cloned the repo, changed the dependencies to devDependencies and added the storybook packages as peerDependencies with "^6.3.0". Afterwards, I builded the package and used `npm link` to use this in my project and this seems to work without any other change.

### Describe the solution you'd like
Publish the package with peerDependencies instead of dependencies, so the using projects are not bound to your fixed version (in this case 6.2.9 )

**Comment by jimdrury** [comment]
Sure, got this releasing with a few other patches later today
