### ISSUE TITLE
@geometricpanda/storybook-addon-badges specifies a range of peer versions which does not fit the @storybook-addons beta

### ISSUE THREAD

**Issue by Tim-arts** [geometricpanda/geometricpanda#35]
# 🐞 bug report

### Affected Package
 @geometricpanda/storybook-addon-badges@0.2.1

### Description
Getting an error while running `npm install` command

## 🔬 Minimal Reproduction
You can reproduct this issue with the latest beta Storybook version (6.4.0-beta.23: `npx sb@next upgrade --prerelease` (upgrade) | `npx sb@next init` (install)). Install your addon into the SB configuration and execute `npm i`, you'll get this error

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/10064887/139496403-886c417b-eb96-4f78-a168-669e2a3d20f6.png)

## 🌍  Your Environment
**Storybook Version:**
6.4.0-beta.23

**@geometricpanda Version:**
0.2.1

It has a workaround which is simply to force the npm install : `npm install --force`

**Comment by jimdrury** [comment]
This should be resolved with 0.2.2
