### ISSUE TITLE
Cannot create custom badges with storybook/vue

### ISSUE THREAD

**Issue by PhilReinking** [geometricpanda/geometricpanda#38]
I tried to add custom badges in the preview.js by using the addParameters function. But this seems to do just nothing? Thought it might be related to the fact that I'm using the VueJS version of storybook?

Here is what I do in preview.js:

```js
import { addParameters } from '@storybook/vue';

addParameters({
  badgesConfig: {
    about: {
      styles: {
        backgroundColor: '#FFF',
        borderColor: '#018786',
        color: '#018786',
      },
      title: 'About',
    },
  },
});
```

Using the about badge in a story, just renders "about" in the storybook frontend, without any styling. It doesn't even use the defined title which would begin with an uppercase letter.

## 🌍  Your Environment

**Storybook Version:**
<pre><code>
@storybook/vue@6.4.22

</code></pre>

**@geometricpanda Version:**
<pre><code>
@geometricpanda/storybook-addon-badges@0.2.1

</code></pre>

**Comment by jimdrury** [comment]
Hi Phil,
I'll need to investigate this as it was designed for Angular and React primarily

I'll take a look this evening though :)

**Comment by PhilReinking** [comment]
@geometricpanda thanks! anything I can assist you with debugging this?

**Comment by jimdrury** [comment]
@PhilReinking hey. just looked into this, worked like a charm for me in Vue 3

I did notice you had:
`import { addParameters } from '@storybook/vue';`

could you try this instead please?
`import { addParameters } from '@storybook/vue3';`

Also once you've configured your badges visually, you need to apply them to your stories 

https://github.com/geometricpanda/geometricpanda/blob/main/libs/storybook-addon-badges/README.md#individual-stories

Going to close the issue, but feel free to comment on it and i'll re-open it if you still have issues
