### ISSUE TITLE
Export Badge Component so it can be used in MDX Docs

### ISSUE THREAD

**Issue by aboutsimon** [geometricpanda/geometricpanda#39]
# 🚀 feature request

### Relevant Package

`@geometricpanda/storybook-addon-badges`

### Description

I would like to explain our usage of Badges in a free form MDX Docs Page. I would be very helpful, if i could just use the [Badge](https://github.com/geometricpanda/geometricpanda/blob/main/libs/storybook-addon-badges/src/lib/blocks/badge.tsx) and maybe the [Badges](https://github.com/geometricpanda/geometricpanda/blob/main/libs/storybook-addon-badges/src/lib/blocks/badges.tsx) components for that.

### Describe the solution you'd like

Include an export of the React components in the package.

**Comment by jimdrury** [comment]
I'm doing some maintenance this week, I'll see if I can get this done alongside

**Comment by jimdrury** [comment]
After investigation, i'm afraid that components used in a MDX cant inherit context from the main Storybook without some pretty ugly config changes
