### ISSUE TITLE
Storybook badges does not work with angular storybook

### ISSUE THREAD

**Issue by decherneyge** [geometricpanda/geometricpanda#49]
# 🐞 bug report

### Affected Package
The issue is caused by package @geometricpanda/storybook-addon-badges

### Is this a regression?
According to the docs it is as the docs state it works with Angular storybook

### Description

When trying to add storybook-addon-badges to a storybook built with angular it errors saying it can not find ` Cannot find module 'react-textarea-autosize' or its corresponding type declarations.`

## 🔬 Minimal Reproduction
https://github.com/decherneyge/basic-angular-storybook-with-badges

## 🔥 Exception or Error
<pre><code>
Error: node_modules/@storybook/components/dist/ts3.9/index.d.ts:278:72 - error TS2307: Cannot find module 'react-textarea-autosize' or its corresponding type declarations.

278     Textarea: import("@storybook/theming").StyledComponent<Omit<import("react-textarea-autosize").TextareaAutosizeProps, keyof InputStyleProps> & InputStyleProps & import("react").RefAttributes<any>, Omit<import("react-textarea-autosize").TextareaAutosizeProps, keyof InputStyleProps> & InputStyleProps, import("@storybook/theming").Theme> & {

</code></pre>

## 🌍  Your Environment

**Storybook Version:**
<pre><code>
6.5.6

</code></pre>

**@geometricpanda Version:**
<pre><code>
0.2.2

</code></pre>

**Anything else relevant?**
n/a

**Comment by jimdrury** [comment]
Thanks for reporting this, I'll take a look tomorrow. Not sure why it's requiring that package as it's not something I'm using - I'll see I guess

**Comment by jimdrury** [comment]
So I had a look, looks like storybook isn't reporting it's dependencies correctly. 

If you npm install the missing package it should fix it. 

Triple checked and it's not one of mine unfortunately.
