### ISSUE TITLE
Make react / react-dom peerDependencies

### ISSUE THREAD

**Issue by MasterOdin** [geometricpanda/geometricpanda#54]
# 🚀 feature request

### Relevant Package

Both packages

### Description
 A clear and concise description of the problem or missing capability...

We are moving to react 18 for our application, and your packages are the only one that's bringing in their own version of react / react-dom. This adds a bit of bloat to our dependency tree in having to install those two dependencies, and also makes us a bit worried about possible weird react collisions depending on how yarn decides to hoist things.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Make `react` and `react-dom` peerDependencies. This is similar to how the official storybook addons are structured (e.g. https://github.com/storybookjs/storybook/blob/v6.5.16-alpha.0/addons/actions/package.json).

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
 
No workaround exists beyond removing the package.

**Comment by jimdrury** [comment]
Hey,
Thanks for reporting this, I'm gonna be doing some maintenance this week to both packages and I hope to have this resolved ASAP.

**Comment by jimdrury** [comment]
Resolved in version 1.0.1

You can find the course code in its new home https://github.com/geometricpanda/storybook-addon-badges
